=== subramaniam97/Lesk/pylesk/senseval/corpora/czech-all-words/trial/all-words.dtd
<!--
	Document definition for an all-words task for senseval. Draft version
	20001209.

        The answers to a given all words document can be provided
        in a simple table of TEXTID, SENSEID pairs, where TEXTIDs
        refer to the id attribute of "head" elements.

        Answers may also be embedded in the document for the purpose
        of distributing "gold standard" corpora or for faciliating
        software processing of all the relevant data.
-->

<!ENTITY agrave "`">
<!ENTITY bsol "\">
<!ENTITY circ "^">
<!ENTITY dollar "$">
<!ENTITY lowbar "_">
<!ENTITY lsqb "[">
<!ENTITY percnt "&#37;">
<!ENTITY rsqb "]">
<!ENTITY verbar "|">


<!ELEMENT corpus (descr?,text+,answer*)>
<!ATTLIST corpus lang CDATA #REQUIRED>

<!-- 
	"descr" is a place to add arbitrary meta info such as where the 
     	data came from, who collected it, etc.  It is an optional item.
 -->
<!ELEMENT descr (#PCDATA)>

<!-- 
	Each corpus contains a set of texts.  Each text has 
   lexical items to be marked up.  In general, lexical items
   will be single continuous words.  However, in some cases, 
   the lexical item may be discontinous and phrasal, in which 
   case we'd like to accurately denote the text that is associated
   with a sense tag.  We do this with an optional satellite tag.

   The docsrc and topic attributes are optional and may be used to
   help track and or index senseval data with respect to its origins. 
 -->
<!ELEMENT text (#PCDATA | head | sat)*>
<!ATTLIST text
          id ID #REQUIRED
	  docsrc ID #IMPLIED
	  topic CDATA #IMPLIED>

<!--

heads are elements with which sense tags are associated.  They
require a unique id, and may be associated with satellites.
 -->

<!ELEMENT head (#PCDATA)>
<!ATTLIST head 
   id ID  #REQUIRED
   sats IDREFS #IMPLIED>

<!ELEMENT sat (#PCDATA)>
<!ATTLIST sat 
          id ID #REQUIRED>

<!-- 
an answer has an explicit reference to it's associated head word 
via the "head" attribute.  senseids may be left blank for distributing
fill in the blank corpora or for answers which mean "don't know". 

More than one answer may be specified per head ID.
-->
<!ELEMENT answer EMPTY>
<!ATTLIST answer 
          head IDREF #REQUIRED  
          senseid  CDATA #IMPLIED>

=== subramaniam97/Lesk/pylesk/senseval/corpora/dutch-all-words/trial/all-words-dutch-trial.xml
<?xml version="1.0"?>
<!DOCTYPE corpus SYSTEM 
	  "/home/antalb/projects/senseval01/all-words.dtd">
<corpus lang="du">
<text id="P2WOESTE">

<head id="P2WOESTE.t0">als</a>
Willem
<head id="P2WOESTE.t1">op</a>
<head id="P2WOESTE.t2">een</a>
avond
zeeroversliedjes
<head id="P2WOESTE.t3">zit</a>
<head id="P2WOESTE.t4">te</a>
<head id="P2WOESTE.t5">spelen</a>
<head id="P2WOESTE.t6">op</a>
<head id="P2WOESTE.t7">zijn</a>
<head id="P2WOESTE.t8">oude</a>
harmonika
,
<head id="P2WOESTE.t9">hoort</a>
hij
<head id="P2WOESTE.t10">een</a>
raar
<head id="P2WOESTE.t11">geluid</a>
boven
<head id="P2WOESTE.t12">zijn</a>
<head id="P2WOESTE.t13">hoofd</a>
.

</text>

<answer head="P2WOESTE.t0" senseid="als_tijd">
<answer head="P2WOESTE.t1" senseid="op_tijd">
<answer head="P2WOESTE.t2" senseid="een_lidwoord">
<answer head="P2WOESTE.t3" senseid="zitten_hww">
<answer head="P2WOESTE.t4" senseid="te_adv">
<answer head="P2WOESTE.t5" senseid="spelen_piano">
<answer head="P2WOESTE.t6" senseid="op_">
<answer head="P2WOESTE.t7" senseid="zijn_bez.vnw">
<answer head="P2WOESTE.t8" senseid="oud_nieuw">
<answer head="P2WOESTE.t9" senseid="horen_luisteren">
<answer head="P2WOESTE.t10" senseid="een_lidwoord">
<answer head="P2WOESTE.t11" senseid="geluid_N">
<answer head="P2WOESTE.t12" senseid="zijn_bez.vnw">
<answer head="P2WOESTE.t13" senseid="hoofd_lichaamsdeel">

</corpus>
