<?xml version="1.0" encoding="ISO-8859-1" standalone="no" ?>
<!DOCTYPE corpus [

<!--
    PLEASE READ THE COPYRIGHT STATEMENT
    **************************************************************
    #############################################################
    EVALUATION CORPUS FOR THE SWEDISH "lexical sample" TASK OF SENSEVAL-2
    File Name: "swedish_lexical_sample_EVAL_corpus.xml"
    File Content:  (i) the DTD for the corpus encoding
                  (ii) 1,527 unannotated instances 
                       The sense-tags have been replaced with "??????"
    ##############################################################
    **************************************************************
    The lexical sample task in SENSEVAL-2 is a word sense disambiguation task
    for particular (preselected) lexical items.
    The Swedish lexical sample consists of 40 lemmas; 
           20 NOUNS
           15 VERBS
            5 ADJECTIVES
    **************************************************************
    The final version of the training corpus was generated the 2001-04-24 
    by Yvonne Cederholm and validated with "xmlnorm" the 2001-04-25 and parsed
    with "Mozilla" the 2001-04-27 by Dimitrios Kokkinakis.
    The responsible person for the annotation of all the instances is
    Assoc. Prof. Jerker Järborg

    The underlying corpus from which all instances were gathered and
    annotated is the Stockholm-Umeå Corpus (SUC) version 1.0
    Copyright SUC: Department of Linguistics, Stockholms University; 
                   Department of Linguistics, Umeå University 
              http://www.ling.su.se/DaLi/Projects/SUC/Index.html
    **************************************************************
    Contact:
        For more information, comments etc. on the SWEDISH SENSEVAL contact:
        Dimitrios.Kokkinakis@svenska.gu.se
        For more information about GLDB/SDB (the lexicon) contact:
        Jerker.Jaerborg@svenska.gu.se
    **************************************************************
    References: 
        GLDB/SDB
         http://spraakdata.gu.se/
         Järborg J. (1999), Lexikon i konfrontation. Research Reports
           from the Department of Swedish, Göteborg University. GU-ISS-99-6.
           (In Swedish)

	SUC:
         Ejerhed, E., Källgren, G., Wennstedt, G., Åström, M. (1992),
           The Linguistic Annotation of the Stockholm-Umeå Corpus Project,
           Technical Report No 33, University of Umeå

        Kokkinakis D., Järborg J. and Cederholm Y. (May, 2001), Swedish
        SENSEVAL; a Developers' Perspective. Proceedings of the NODALIDA
        (Nordiska Datalingvistikdagarna) Conference. Uppsala, Sweden.
        http://svenska.gu.se/~svedk/publics/sensevalswe.pdf
    **************************************************************
-->

<!--
   COPYRIGHT STATEMENT:
     The content of this file is being provided to you, the LICENSEE, by the 
     Språkdata (Department of Swedish, Göteborg University) under the 
     following license.  By obtaining, using and/or copying this file, you 
     agree that you have read, understood, and will comply with these terms
     and conditions:  

     Permission to use and/or copy the content of this file
     and its documentation for any purpose and without fee or royalty is
     hereby granted, provided that you agree to comply with the following
     copyright notice and statements, including the disclaimer, and that
     the same appear on ALL copies of the file and documentation, including 
     modifications that you make for internal use or for distribution:

     Copyright 2001 by Språkdata and the Göteborg University.
     All rights reserved.  

     THIS FILE CONTENT IS PROVIDED "AS IS", AND Språkdata MAKES NO 
     REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED. By way of example,
     but not limitation, Språkdata MAKES NO REPRESENTATIONS OR WARRANTIES OF 
     MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF 
     THE LICENSED FILE OR DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY 
     PATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.   

     The name of the Språkdata may NOT be used in advertising or publicity
     pertaining to distribution of the file content. Title to copyright in
     this software and any associated documentation shall at all times remain
     with Språkdata, and LICENSEE agrees to preserve same.
-->

<!-- latin2 and greek entity sets included -->
<!ENTITY agr     "&#945;" ><!--small alpha, Greek, U03B1 -->
<!ENTITY Agr     "&#913;" ><!--capital Alpha, Greek, U0391 -->
<!ENTITY bgr     "&#946;" ><!--small beta, Greek, U03B2 -->
<!ENTITY Bgr     "&#914;" ><!--capital Beta, Greek, U0392 -->
<!ENTITY ggr     "&#947;" ><!--small gamma, Greek, U03B3 -->
<!ENTITY Ggr     "&#915;" ><!--capital Gamma, Greek, U0393 -->
<!ENTITY dgr     "&#948;" ><!--small delta, Greek, U03B4 -->
<!ENTITY Dgr     "&#916;" ><!--capital Delta, Greek, U0394 -->
<!ENTITY egr     "&#949;" ><!--small epsilon, Greek, U03B5 -->
<!ENTITY Egr     "&#917;" ><!--capital Epsilon, Greek, U0395 -->
<!ENTITY zgr     "&#950;" ><!--small zeta, Greek, U03B6 -->
<!ENTITY Zgr     "&#918;" ><!--capital Zeta, Greek, U0396 -->
<!ENTITY eegr    "&#951;" ><!--small eta, Greek, U03B7 -->
<!ENTITY EEgr    "&#919;" ><!--capital Eta, Greek, U0397 -->
<!ENTITY thgr    "&#952;" ><!--small theta, Greek, U03B8 -->
<!ENTITY THgr    "&#920;" ><!--capital Theta, Greek, U0398 -->
<!ENTITY igr     "&#953;" ><!--small iota, Greek, U03B9 -->
<!ENTITY Igr     "&#921;" ><!--capital Iota, Greek, U0399 -->
<!ENTITY kgr     "&#954;" ><!--small kappa, Greek, U03BA -->
<!ENTITY Kgr     "&#922;" ><!--capital Kappa, Greek, U039A -->
<!ENTITY lgr     "&#955;" ><!--small lambda, Greek, U03BB -->
<!ENTITY Lgr     "&#923;" ><!--capital Lambda, Greek, U039B -->
<!ENTITY mgr     "&#956;" ><!--small mu, Greek, U03BC -->
<!ENTITY Mgr     "&#924;" ><!--capital Mu, Greek, U039C -->
<!ENTITY ngr     "&#957;" ><!--small nu, Greek, U03BD -->
<!ENTITY Ngr     "&#925;" ><!--capital Nu, Greek, U039D -->
<!ENTITY xgr     "&#958;" ><!--small xi, Greek, U03BE -->
<!ENTITY Xgr     "&#926;" ><!--capital Xi, Greek, U039E -->
<!ENTITY ogr     "&#959;" ><!--small omicron, Greek, U03BF -->
<!ENTITY Ogr     "&#927;" ><!--capital Omicron, Greek, U039F -->
<!ENTITY pgr     "&#960;" ><!--small pi, Greek, U03C0 -->
<!ENTITY Pgr     "&#928;" ><!--capital Pi, Greek, U03A0 -->
<!ENTITY rgr     "&#961;" ><!--small rho, Greek, U03C1 -->
<!ENTITY Rgr     "&#929;" ><!--capital Rho, Greek, U03A1 -->
<!ENTITY sfgr    "&#962;" ><!--final small sigma, Greek, U03C2 --> 
<!ENTITY sgr     "&#963;" ><!--small sigma, Greek, U03C3 -->
<!ENTITY Sgr     "&#931;" ><!--capital Sigma, Greek, U03A3 -->
<!ENTITY tgr     "&#964;" ><!--small tau, Greek, U03C4 -->
<!ENTITY Tgr     "&#932;" ><!--capital Tau, Greek, U03A4 -->
<!ENTITY ugr     "&#965;" ><!--small upsilon, Greek, U03C5 -->
<!ENTITY Ugr     "&#933;" ><!--capital Upsilon, Greek, U03A5 -->
<!ENTITY phgr    "&#966;" ><!--small phi, Greek, U03C6 -->
<!ENTITY PHgr    "&#934;" ><!--capital Phi, Greek, U03A6 -->
<!ENTITY khgr    "&#967;" ><!--small chi, Greek, U03C7 -->
<!ENTITY KHgr    "&#935;" ><!--capital Chi, Greek, U03A7 -->
<!ENTITY psgr    "&#968;" ><!--small psi, Greek, U03C8 -->
<!ENTITY PSgr    "&#936;" ><!--capital Psi, Greek, U03A8 -->
<!ENTITY ohgr    "&#969;" ><!--small omega, Greek, U03C9 -->
<!ENTITY OHgr    "&#937;" ><!--capital Omega, Greek, U03A9 -->
 

<!-- (C) International Organization for Standardization 1986
     Permission to copy in any form is granted for use with
     conforming SGML systems and applications as defined in
     ISO 8879, provided this notice is included in all copies.
-->


<!-- Character entity set. Typical invocation:
     <!ENTITY % ISOlat2 PUBLIC
       "ISO 8879:1986//ENTITIES Added Latin 2//EN//XML"
       "ISOlat2.pen">
     %ISOlat2;
-->
<!-- This version of the entity set can be used with any SGML document
     which uses ISO 10646 as its document character set. 
     This includes XML documents and ISO HTML documents.
     This entity set uses hexadecimal numeric character references. 
          
     Creator: Rick Jelliffe, Allette Systems
     
     Version: 1997-07-07
-->
<!ENTITY abreve "&#x103;" ><!--=small a, breve-->
<!ENTITY Abreve "&#x102;" ><!--=capital A, breve-->
<!ENTITY amacr  "&#x101;" ><!--=small a, macron-->
<!ENTITY Amacr  "&#x100;" ><!--=capital A, macron-->
<!ENTITY aogon  "&#x105;" ><!--=small a, ogonek-->
<!ENTITY Aogon  "&#x104;" ><!--=capital A, ogonek-->
<!ENTITY cacute "&#x107;" ><!--=small c, acute accent-->
<!ENTITY Cacute "&#x106;" ><!--=capital C, acute accent-->
<!ENTITY ccaron "&#x10D;" ><!--=small c, caron-->
<!ENTITY Ccaron "&#x10C;" ><!--=capital C, caron-->
<!ENTITY ccirc  "&#x109;" ><!--=small c, circumflex accent-->
<!ENTITY Ccirc  "&#x108;" ><!--=capital C, circumflex accent-->
<!ENTITY cdot   "&#x10B;" ><!--=small c, dot above-->
<!ENTITY Cdot   "&#x10A;" ><!--=capital C, dot above-->
<!ENTITY dcaron "&#x10F;" ><!--=small d, caron-->
<!ENTITY Dcaron "&#x10E;" ><!--=capital D, caron-->
<!ENTITY dstrok "&#x111;" ><!--=small d, stroke-->
<!ENTITY Dstrok "&#x110;" ><!--=capital D, stroke-->
<!ENTITY ecaron "&#x11B;" ><!--=small e, caron-->
<!ENTITY Ecaron "&#x11A;" ><!--=capital E, caron-->
<!ENTITY edot   "&#x117;" ><!--=small e, dot above-->
<!ENTITY Edot   "&#x116;" ><!--=capital E, dot above-->
<!ENTITY emacr  "&#x113;" ><!--=small e, macron-->
<!ENTITY Emacr  "&#x112;" ><!--=capital E, macron-->
<!ENTITY eogon  "&#x119;" ><!--=small e, ogonek-->
<!ENTITY Eogon  "&#x118;" ><!--=capital E, ogonek-->
<!ENTITY gacute "&#x1F5;" ><!--=small g, acute accent-->
<!ENTITY gbreve "&#x11F;" ><!--=small g, breve-->
<!ENTITY Gbreve "&#x11E;" ><!--=capital G, breve-->
<!ENTITY Gcedil "&#x122;" ><!--=capital G, cedilla-->
<!ENTITY gcirc  "&#x11D;" ><!--=small g, circumflex accent-->
<!ENTITY Gcirc  "&#x11C;" ><!--=capital G, circumflex accent-->
<!ENTITY gdot   "&#x121;" ><!--=small g, dot above-->
<!ENTITY Gdot   "&#x120;" ><!--=capital G, dot above-->
<!ENTITY hcirc  "&#x125;" ><!--=small h, circumflex accent-->
<!ENTITY Hcirc  "&#x124;" ><!--=capital H, circumflex accent-->
<!ENTITY hstrok "&#x127;" ><!--=small h, stroke-->
<!ENTITY Hstrok "&#x126;" ><!--=capital H, stroke-->
<!ENTITY Idot   "&#x130;" ><!--=capital I, dot above-->
<!ENTITY Imacr  "&#x12A;" ><!--=capital I, macron-->
<!ENTITY imacr  "&#x12B;" ><!--=small i, macron-->
<!ENTITY ijlig  "&#x133;" ><!--=small ij ligature-->
<!ENTITY IJlig  "&#x132;" ><!--=capital IJ ligature-->
<!ENTITY inodot "&#x131;" ><!--=small i without dot-->
<!ENTITY iogon  "&#x12F;" ><!--=small i, ogonek-->
<!ENTITY Iogon  "&#x12E;" ><!--=capital I, ogonek-->
<!ENTITY itilde "&#x129;" ><!--=small i, tilde-->
<!ENTITY Itilde "&#x128;" ><!--=capital I, tilde-->
<!ENTITY jcirc  "&#x135;" ><!--=small j, circumflex accent-->
<!ENTITY Jcirc  "&#x134;" ><!--=capital J, circumflex accent-->
<!ENTITY kcedil "&#x137;" ><!--=small k, cedilla-->
<!ENTITY Kcedil "&#x136;" ><!--=capital K, cedilla-->
<!ENTITY kgreen "&#x138;" ><!--=small k, Greenlandic-->
<!ENTITY lacute "&#x13A;" ><!--=small l, acute accent-->
<!ENTITY Lacute "&#x139;" ><!--=capital L, acute accent-->
<!ENTITY lcaron "&#x13E;" ><!--=small l, caron-->
<!ENTITY Lcaron "&#x13D;" ><!--=capital L, caron-->
<!ENTITY lcedil "&#x13C;" ><!--=small l, cedilla-->
<!ENTITY Lcedil "&#x13B;" ><!--=capital L, cedilla-->
<!ENTITY lmidot "&#x140;" ><!--=small l, middle dot-->
<!ENTITY Lmidot "&#x139;" ><!--=capital L, middle dot-->
<!ENTITY lstrok "&#x142;" ><!--=small l, stroke-->
<!ENTITY Lstrok "&#x141;" ><!--=capital L, stroke-->
<!ENTITY nacute "&#x144;" ><!--=small n, acute accent-->
<!ENTITY Nacute "&#x143;" ><!--=capital N, acute accent-->
<!ENTITY eng    "&#x14B;" ><!--=small eng, Lapp-->
<!ENTITY ENG    "&#x14A;" ><!--=capital ENG, Lapp-->
<!ENTITY napos  "&#x149;" ><!--=small n, apostrophe-->
<!ENTITY ncaron "&#x148;" ><!--=small n, caron-->
<!ENTITY Ncaron "&#x147;" ><!--=capital N, caron-->
<!ENTITY ncedil "&#x146;" ><!--=small n, cedilla-->
<!ENTITY Ncedil "&#x145;" ><!--=capital N, cedilla-->
<!ENTITY odblac "&#x151;" ><!--=small o, double acute accent-->
<!ENTITY Odblac "&#x150;" ><!--=capital O, double acute accent-->
<!ENTITY Omacr  "&#x14C;" ><!--=capital O, macron-->
<!ENTITY omacr  "&#x14D;" ><!--=small o, macron-->
<!ENTITY oelig  "&#x153;" ><!--=small oe ligature-->
<!ENTITY OElig  "&#x152;" ><!--=capital OE ligature-->
<!ENTITY racute "&#x155;" ><!--=small r, acute accent-->
<!ENTITY Racute "&#x154;" ><!--=capital R, acute accent-->
<!ENTITY rcaron "&#x159;" ><!--=small r, caron-->
<!ENTITY Rcaron "&#x158;" ><!--=capital R, caron-->
<!ENTITY rcedil "&#x157;" ><!--=small r, cedilla-->
<!ENTITY Rcedil "&#x156;" ><!--=capital R, cedilla-->
<!ENTITY sacute "&#x15B;" ><!--=small s, acute accent-->
<!ENTITY Sacute "&#x158;" ><!--=capital S, acute accent-->
<!ENTITY scaron "&#x161;" ><!--=small s, caron-->
<!ENTITY Scaron "&#x160;" ><!--=capital S, caron-->
<!ENTITY scedil "&#x15F;" ><!--=small s, cedilla-->
<!ENTITY Scedil "&#x15E;" ><!--=capital S, cedilla-->
<!ENTITY scirc  "&#x15C;" ><!--=small s, circumflex accent-->
<!ENTITY Scirc  "&#x15D;" ><!--=capital S, circumflex accent-->
<!ENTITY tcaron "&#x165;" ><!--=small t, caron-->
<!ENTITY Tcaron "&#x164;" ><!--=capital T, caron-->
<!ENTITY tcedil "&#x162;" ><!--=small t, cedilla-->
<!ENTITY Tcedil "&#x163;" ><!--=capital T, cedilla-->
<!ENTITY tstrok "&#x167;" ><!--=small t, stroke-->
<!ENTITY Tstrok "&#x166;" ><!--=capital T, stroke-->
<!ENTITY ubreve "&#x16D;" ><!--=small u, breve-->
<!ENTITY Ubreve "&#x16C;" ><!--=capital U, breve-->
<!ENTITY udblac "&#x171;" ><!--=small u, double acute accent-->
<!ENTITY Udblac "&#x170;" ><!--=capital U, double acute accent-->
<!ENTITY umacr  "&#x16B;" ><!--=small u, macron-->
<!ENTITY Umacr  "&#x16A;" ><!--=capital U, macron-->
<!ENTITY uogon  "&#x173;" ><!--=small u, ogonek-->
<!ENTITY Uogon  "&#x172;" ><!--=capital U, ogonek-->
<!ENTITY uring  "&#x16F;" ><!--=small u, ring-->
<!ENTITY Uring  "&#x16E;" ><!--=capital U, ring-->
<!ENTITY utilde "&#x169;" ><!--=small u, tilde-->
<!ENTITY Utilde "&#x168;" ><!--=capital U, tilde-->
<!ENTITY wcirc  "&#x175;" ><!--=small w, circumflex accent-->
<!ENTITY Wcirc  "&#x174;" ><!--=capital W, circumflex accent-->
<!ENTITY ycirc  "&#x177;" ><!--=small y, circumflex accent-->
<!ENTITY Ycirc  "&#x176;" ><!--=capital Y, circumflex accent-->
<!ENTITY Yuml   "&#x178;" ><!--=capital Y, dieresis or umlaut mark-->
<!ENTITY zacute "&#x17A;" ><!--=small z, acute accent-->
<!ENTITY Zacute "&#x179;" ><!--=capital Z, acute accent-->
<!ENTITY zcaron "&#x1FD;" ><!--=small z, caron-->
<!ENTITY Zcaron "&#x17E;" ><!--=capital Z, caron-->
<!ENTITY zdot   "&#x17C;" ><!--=small z, dot above-->
<!ENTITY Zdot   "&#x17B;" ><!--=capital Z, dot above-->


<!-- A corpus is divided up by lexical item and is associated
     with a language (should maybe use isoXXX character set encodings)
-->

<!ELEMENT		corpus (lexelt+)>
<!ATTLIST		corpus lang CDATA #REQUIRED>

<!ELEMENT		lexelt (instance+)>

<!ATTLIST		lexelt item CDATA #REQUIRED>

<!--  
Instances must denote exactly one head element, which may have satellites in the case of 
(discontinuous) multi word expressions.  Answers will be associated with the instances 
by the instances 'id' attribute.
-->

<!ELEMENT		instance (answer*, context)>
<!ATTLIST		instance
          		id  ID #REQUIRED>

<!-- an answer has an explicit reference to the associated instance
     it must specify the instance by referring to it's id 
-->

<!ELEMENT		answer EMPTY>
<!ATTLIST		answer 
         		instance IDREF #REQUIRED  
         		senseid  CDATA #IMPLIED>

<!ELEMENT		context (#PCDATA | head | sat)*>
<!ELEMENT		head (#PCDATA)>
<!ATTLIST		head 
   			sats IDREFS #IMPLIED>

<!ELEMENT		sat (#PCDATA)>
<!ATTLIST		sat 
          		id ID #REQUIRED>
]>

<corpus lang="swe">
	<lexelt item="följa">
	<instance id="följa.0">
	<answer instance="följa.0" senseid="??????"/>
	<context>Mona Malmros [ Faxa inte journaler hur som helst ] Journaler med personuppgifter är sekretessbelagda. När journaler överförs per telefax finns risk för att obehöriga kan ta del av dem , inte minst om den som faxar råkar knappa in fel nummer. För att öka säkerheten uppmanar hälso- och sjukvårdsnämndens stab dem som sänder och tar emot telefax att <head>följa</head>  vissa regler. Allra helst ska journaler inte faxas alls utan sändas i slutet kuvert med internposten eller i rekommenderat brev. Om det är så bråttom att telefax måste användas bör uppgifter om namn, personnummer, adress med mera strykas över. </context> 
	</instance>
	<instance id="följa.1">
	<answer instance="följa.1" senseid="??????"/>
	<context>Detta stod färdigt 1630 , och var putsat i rött , eftersom Johan III enligt uppgift älskade denna färg. Läsaren förs vidare genom storhetstiden och drottning Kristina till den stora slottsbranden 1702 , återuppbyggnaden i mitten på samma sekel , då renässansen krävde vit puts , vimplar och flärd. Man får <head>följa</head>  historiens gång ända fram till våra dagars slott, hur det använts och hur det förändrats. Uppsala slott har skiftat utseende många gånger. Till exempel när universitetsbiblioteket Carolina Rediviva skulle uppföras, i början på 1800-talet. </context> 
	</instance>
	<instance id="följa.2">
	<answer instance="följa.2" senseid="??????"/>
	<context>Stjärnorna spred ett blekt skimmer över de sovandes ansikten på däcket , dyningarna hävde sig långsamt under oss. Gubben mätte oss med blicken : - Kanske kan jag hjälpa er. Han reste sig och tecknade åt oss att <head>följa</head>  med akterut där han hade sina ägodelar. Tyst, för att inte väcka någon, tömde han en säck med grytor, filtar, böcker: ett helt hushåll.- Kryp ner här, sa han och pekade på Jakov. </context> 
	</instance>
	<instance id="följa.3">
	<answer instance="följa.3" senseid="??????"/>
	<context>[ Sekretess ] 5 § Enskildas förhållanden till värdepappersfond , fondbolag och förvaringsinstitut får inte obehörigen röjas. I det allmännas verksamhet tillämpas i stället bestämmelserna i sekretesslagen ( 1980:100 ). [ Fondbolag ] 6 § För fondbolag gäller vad som är föreskrivet om aktiebolag i allmänhet om inte annat <head>följer</head>  av denna lag. Ett fondbolag skall ha ett aktiekapital som med hänsyn till verksamhetens omfattning är tillräckligt stort. Regeringen eller, efter regeringens bemyndigande, bankinspektionen skall meddela närmare föreskrifter om aktiekapitalets storlek. </context> 
	</instance>
	<instance id="följa.4">
	<answer instance="följa.4" senseid="??????"/>
	<context>Det är ett fysikaliskt fenomen som beror på att en våg går långsammare när den kommer in på grunt vatten. Man kan se det som ett slags bromsande friktion mot bottnen. Vi kan föreställa oss att vi <head>följer</head>  med en bred vågfront som är på väg snett in mot en strandlinje på höger sida. Så länge vattendjupet är större än våglängden, dvs större än avståndet mellan två vågtoppar, är vågens hastighet oberoende av det exakta djupet och den fortsätter rakt fram. När sedan den högra kanten av vågfronten nått grunt vatten rör den sig långsammare framåt, eftersom den" tar i bottnen". </context> 
	</instance>
	<instance id="följa.5">
	<answer instance="följa.5" senseid="??????"/>
	<context>Av Yvonne Butfors , Per Andersson , Simon Lefvert och Katarina Elghuvud. [ En snabbkurs i kapitalism ] SAN FRANCISCO ( SvD ) Michail Gorbatjov får sitt handelsavtal med USA - om nu inte den amerikanska kongressen sätter käppar i hjulen. Följdriktigt avslutade han sin nordamerikanska vecka med en snabbkurs i kapitalism : sju timmar i " svenskstaten " Minnesota <head>följt</head>  av ett knappt dygn i Kaliforniens San Francisco, som med sitt Silicon Valley är den amerikanska dataindustrins centrum. Resmålen var ingen slump. Den gemensamma presskonferensen med George Bush var slutpunkten för den sovjetiske presidentens officiella program. </context> 
	</instance>
	<instance id="följa.6">
	<answer instance="följa.6" senseid="??????"/>
	<context>Följande är ett antal elementära fall där två drag typiskt etablerar en enda konsekvens ( jfr Sacks begrepp adjacency pair ) : ( 5 ) a. En fråga följt av ett svar b. Ett drag <head>följt</head>  av en reaktion på det draget c. Ett drag föregånget av ett varsel( pre, Levinson 1983:345-364) om det draget d. Ett drag föregånget av en begäran om det draget e. </context> 
	</instance>
	<instance id="följa.7">
	<answer instance="följa.7" senseid="??????"/>
	<context>Det han gjorde såg självklart och enkelt ut , men hon visste av egen erfarenhet att det inte var så. Han tvekade inte , det fanns inte tillstymmelse till den där lilla fördröjningen som hon själv kunde känna inför ett avgörande. Och den mannen hade hon nu uttalade order att tygla , i och med att skjuta om han inte <head>följde</head>  givna instruktioner. Hon skrattade plötsligt till. Den tanke som slagit henne var att Carl skulle se väldigt förvånad ut om hon sköt honom. </context> 
	</instance>
	<instance id="följa.8">
	<answer instance="följa.8" senseid="??????"/>
	<context>Ljudupptagningen är perfekt , atmosfären förmedlas helt tillfredsställande och plattan fyller alla krav man rimligen kan ha på ett projekt som detta. Med tanke på den rovdrift de flesta avlidna storheter utsätts för av kommersiella skäl är de här plattorna väl värda att propagera för. T_o_m albumtexten , skriven av gitarristen och journalisten Lee Underwood som <head>följde</head>  Buckley under hela hans karriär, är exemplarisk. Ömsint och korrekt beskriver han Buckley och hans musik utan överord och nostalgiskt trams. LÅT VARA ATT Dream Letter inte är den perfekta introduktionen till Buckley som artist. </context> 
	</instance>
	<instance id="följa.9">
	<answer instance="följa.9" senseid="??????"/>
	<context>Och allting var värmens verk. Det var de flesta överens om. Det var värmen som tillsåg att man dagligen framåt lunch kunde se en tant bli utburen och placerad på en köksstol vid Kocksgatan 3 , att man såg henne sitta där sen och hälsa på folk med den friska halvan av ansiktet medan Bertil Perrolf hördes spela skivor till kaffet , spela på och snacka tills Riksronden kom , <head>följt</head>  av Småbarnskvarten. Det var gripande kanske, men inget att bekymra sig om. Lugnt. </context> 
	</instance>
	<instance id="följa.10">
	<answer instance="följa.10" senseid="??????"/>
	<context>Utredningen anser att det i allmänhet skulle innebära en förenkling om ändringar av skattepliktsbestämmelserna föranleder särskilda övergångsbestämmelser i stället för den nuvarande regleringen i 4 § andra stycket ML ( jfr prop. 1978/79:141 s. 41 f angående övergångseffekter vid ändringar av beskattningens omfattning eller storlek ). [ Tredje stycket ( införsel ) ] I stycket anges att vid införsel gäller i stället bestämmelserna i tullagen ( 1987:1065 ) om tull. I ML <head>följer</head>  detsamma av den allmänna hänvisningen till tullagen i 58§ första stycket andra meningen. Vad som sagts under den föregående rubriken om betydelsen av tidpunkten för skattskyldighetens inträde har motsvarande tillämpning vid införsel.[ 10 kap. Rätt för vissa icke skattskyldiga till återbetalning av skatt][ 1-4§§] Paragraferna motsvarar 3-5 och 10§§ lagen( 1991:119) om återbetalning av mervärdeskatt till utländska företagare( prop. 1990/91:72, SkU 13, rskr. 122). </context> 
	</instance>
	<instance id="följa.11">
	<answer instance="följa.11" senseid="??????"/>
	<context>I samma proposition görs dock gällande att interna förvaltningsbeslut som avser bara en kort tidsperiod kan betraktas som beslut i särskilda fall. Normbegreppet i RF avser sammanfattningsvis ensidiga diktat från riksdag , regering , förvaltningsmyndigheter , kommuner och kyrkliga organ. För att ge en ram för den fortsatta framställningen <head>följer</head>  nedan en kortfattad och allmänt hållen genomgång av normgivningskompetensens fördelning enligt regeringsformen. Det finns även anledning att ge några kommentarer till regler som faller utanför begreppet föreskrift enligt grundlagen. 4.2.2 Normgivningsmaktens fördelning m_m[ Normgivningsmaktens fördelning enligt RF 8 kap kan beskrivas som en komplicerad växelverkan mellan huvudsakligen riksdagen och regeringen som även berör förvaltningsmyndigheterna. </context> 
	</instance>
	<instance id="följa.12">
	<answer instance="följa.12" senseid="??????"/>
	<context>[ Särskilt angående personer som hör hemma i utlandet ] Av 4 kap. 2 och 3 §§ NML framgår att den som är skattskyldig till inkomstskatt här i landet för inkomst av näringsverksamhet m.m. anses bedriva yrkesmässig verksamhet här enligt NML. Även en i utlandet hemmahörande person med fast driftställe här i landet är skattskyldig till inkomstskatt för den inkomst som hänför sig till omsättning från detta driftställe ( s.k. inskränkt skattskyldig ). Det <head>följer</head>  av 53§ 1 mom. KL och punkt 1 av anvisningarna därtill samt 6§ 1 mom. SIL. Enligt dessa bestämmelser avgörs när en person skall anses ha en sådan anknytning till Sverige att han är skattskyldig för inkomst. En inskränkt skattskyldig person kan därmed bli skattskyldig till mervärdesskatt enligt 1§ 1 och 2§ 1 NML för omsättningen från nämnda driftställe. </context> 
	</instance>
	<instance id="följa.13">
	<answer instance="följa.13" senseid="??????"/>
	<context>Politiska bedömare ser henne som en tänkbar regeringsmedlem. Nedanstående omdöme om Hillary Clinton har på sistone hörts mer än en gång : - Det är krut i henne , precis vad vi behöver i Vita huset. Leif-Åke Josefsson [ Per och Nina om uppfostran : ] [ Omöjligt att <head>följa</head>  någon ideologi] Per och Nina gifte sig tidigt. I höst har de varit gifta med varann i 25 år. De väntade avsiktligt med barn ända till de var i 30-årsåldern. </context> 
	</instance>
	<instance id="följa.14">
	<answer instance="följa.14" senseid="??????"/>
	<context>Därefter konstrueras fjärde proportionalen till ED , B1D och A1D , som ger DF och därmed F. Tangenten ritas till cirkeln genom F ; konstruktionen ger B , ger A , ger C. Beviset för att BC är parallell med DE , slutligen , tillgår nu så att man konstaterar , att på grund av konstruktionen , triangeln BDF är likformig med triangeln EDA ( VI.6 , första likformighetsfallet , se 5.7.8.4 ; ty genom konstruktionen och av kordasatsen , tillämpad på kordorna A1DB1 och ADB , <head>följer</head>  att ED är till BD som AD till DF, och vertikalvinklarna BDF och EDA är lika). Därmed är vinkeln FBD lika med vinkeln AED. Men eftersom FB är tangent, är vinkeln FBD lika med vinkeln C( III.32 igen!) och därmed vinkeln AED lika med vinkeln C. </context> 
	</instance>
	<instance id="följa.15">
	<answer instance="följa.15" senseid="??????"/>
	<context>En ansökan skall innehålla uppgift om 1. de företag som ansökningen avser , deras verksamhet och ekonomiska ställning , 2. ändamålet med stödet och de skäl i övrigt som åberopas för ansökningen , och 3. svenskt och norskt statligt stöd i annan form har sökts eller beviljats för de projekt som ansökningen avser. Sökanden skall i övrigt lägga fram den utredning som fonden finner behövlig. 16 § Fonden skall <head>följa</head>  verksamheten hos dem som har erhållit stöd och därvid utöva tillsyn av att villkoren iakttas.[ Arbetslivsfondens organisation m.m.] Dir. 1990:7 Beslut vid regeringssammanträde 1990-01-25 Chefen för arbetsmarknadsdepartementet, statsrådet Sahlin, anför.[ </context> 
	</instance>
	<instance id="följa.16">
	<answer instance="följa.16" senseid="??????"/>
	<context>Den klassiska romerska lyriken med Horatius som främsta företrädare hade emellertid redan förlorat denna symbios med musiken , och under de följande tvåtusen åren har det överväldigande flertalet av alla lyriska dikter skrivits utan direkt förbindelse med toner. De medeltida trubadurerna och balladdiktarna var visserligen kompositörer lika mycket som poeter , och enstaka modernare " trubadurer " har också blivit namnkunniga - Bellman och Evert Taube t_ex. Men i stort sett har den västerländska poesin <head>följt</head>  romarnas och inte grekernas exempel och bygger på det talade och efterhand mer och mer också det lästa ordet, mera sällan på sång. Att många sentida lyriska dikter i efterhand tonsatts av andra än författaren är en helt annan sak. Den rent musikaliska innebörden i ordet" lyrisk" lever dock kvar i flera sammanhang. </context> 
	</instance>
	<instance id="följa.17">
	<answer instance="följa.17" senseid="??????"/>
	<context>Möjligen beror det på att de flesta studierna företas i en tidsperiod som närmar sig historisk tid och som därigenom delvis är känd genom andra källor. Möjligen beror det på att den metod- och teoriutveckling vi finner inom feminismen som helhet grundar sig på studiet av vår egen tid , och att man helt enkelt inte i arkeologiska sammanhang tagit hänsyn till att man behandlar ett samhälle från en helt annan tid och av helt annat slag än vårt eget. Det <head>följer</head>  med det dikotomiserande betraktelsesättet att könsrelationer ses som relationer mellan förtryckta( kvinnor) och förtryckare( män). Att utan vidare studera förhistoriska samhällens genusrelationer i termer av makt förutsätter igen att könsrollsmönstret är statiskt. Modellen är hämtad direkt från vårt samhälle och projicerad på forntiden. </context> 
	</instance>
	<instance id="följa.18">
	<answer instance="följa.18" senseid="??????"/>
	<context>Flickan som var 18 år hette Siv Eriksson och bodde med sina föräldrar på Åsögatan 157 i Stockholm. Hon arbetade i en mjölkaffär mitt över gatan. Günther hade fått <head>följa</head>  henne hem på kvällen från Skansen. De hade åkt med färjan från Gröna Lund till Räntmästartrappan på Skeppsbron och hade sedan promenerat upp på Söders höjder. De hade gått Katarinavägen upp, tätt omslingrade och hade slutligen satt sig på en bänk i en park vid Tjärhovsgatan. </context> 
	</instance>
	<instance id="följa.19">
	<answer instance="följa.19" senseid="??????"/>