<?xml version="1.0" encoding="ISO-8859-1" standalone="no" ?>

<!--
    PLEASE READ THE COPYRIGHT STATEMENT
    **************************************************************
    ##############################################################
    LEXICON FILE FOR THE SWEDISH "lexical sample" TASK OF SENSEVAL-2
    File Name: "swedish_lexical_sample_LEXICON.xml"
    File Content: (i) the DTD for lexicon encoding
                 (ii) 40 base forms, 145 senses, 304 sub-senses
    ##############################################################
    **************************************************************
    The lexical sample task in SENSEVAL-2 is a word sense disambiguation
    task for particular (preselected) lexical items.
    The Swedish lexical sample consists of 40 lemmas; 
           20 NOUNS
	   15 VERBS
	    5 ADJECTIVES
    **************************************************************
    The lexicon was generated the 2001-04-24 from GLDB/SDB by
    Yvonne Cederholm and validated with "xmlnorm" the 2001-04-25
    by Dimitrios Kokkinakis
    **************************************************************
    Contact:
        For more information, comments etc. on the SWEDISH SENSEVAL contact:
        Dimitrios.Kokkinakis@svenska.gu.se
        For more information about GLDB/SDB contact:
        Jerker.Jaerborg@svenska.gu.se
    References: 
        GLDB/SDB: http://spraakdata.gu.se/
        Järborg J. (1999), Lexikon i konfrontation. Research Reports
          from the Department of Swedish, Göteborg University. GU-ISS-99-6.
          (In Swedish); http://svenska.gu.se/~svedk/resrapp/konfront.pdf

        Kokkinakis D., Järborg J. and Cederholm Y. (May, 2001), Swedish
          SENSEVAL; a Developers' Perspective. Proceedings of the NODALIDA
          (Nordiska Datalingvistikdagarna) Conference. Uppsala, Sweden;
          http://svenska.gu.se/~svedk/publics/swe_senseval.pdf
    **************************************************************
-->

<!--
   COPYRIGHT STATEMENT:
     The content of this file is being provided to you, the LICENSEE, by the 
     Språkdata (Department of Swedish, Göteborg University) under the 
     following license.  By obtaining, using and/or copying this file, you 
     agree that you have read, understood, and will comply with these terms
     and conditions:  

     Permission to use and/or copy the content of this file
     and its documentation for any purpose and without fee or royalty is
     hereby granted, provided that you agree to comply with the following
     copyright notice and statements, including the disclaimer, and that
     the same appear on ALL copies of the file and documentation, including 
     modifications that you make for internal use or for distribution:

     Copyright 2001 by Språkdata and the Göteborg University.
     All rights reserved.  

     THIS FILE CONTENT IS PROVIDED "AS IS", AND Språkdata MAKES NO 
     REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED. By way of example,
     but not limitation, Språkdata MAKES NO REPRESENTATIONS OR WARRANTIES OF 
     MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF 
     THE LICENSED FILE OR DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY 
     PATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.   

     The name of the Språkdata may NOT be used in advertising or publicity
     pertaining to distribution of the file content. Title to copyright in
     this software and any associated documentation shall at all times remain
     with Språkdata, and LICENSEE agrees to preserve same.
-->

<!-- 
    A lexicon is divided up by lexical items (for Swedish lemma-entries) 
    and is associated with a language (should use ISO-XXXX character 
    set encodings)
-->

<!DOCTYPE lexicon [
<!ELEMENT lexicon (lemma-entry+)>
<!ATTLIST lexicon lang CDATA #REQUIRED>

<!ELEMENT lemma-entry		(lexeme+)>
<!ATTLIST lemma-entry		form		CDATA		#REQUIRED
	    		     	pos		(n|v|a)		"n"
				inflection	CDATA		#REQUIRED
                   		id		ID		#REQUIRED>

<!--  The 'lexemes' (senses) and 'cycles' (sub-senses) must denote exactly
      one head element. One 'lemma' (base form) can have 1 or more 'lexemes'
      (since we provide only polysemous entries); and 1 lexeme can have 0 or
      more cycles. 
-->

<!ELEMENT lexeme 	(definition, definition-ext?, compound*, 
					synt-example*, cycle*, valency*, comment*)>
<!ATTLIST lexeme	id  ID #REQUIRED>

<!ELEMENT cycle		(trans, definition?, definition-ext?, compound*, 
					synt-example*, valency*, comment*)>
<!ATTLIST cycle		id  ID #REQUIRED>

<!ELEMENT definition		(#PCDATA)>
<!ELEMENT definition-ext	(#PCDATA)>
<!ELEMENT synt-example	(#PCDATA)>
<!ELEMENT compound		(#PCDATA)>
<!ELEMENT valency		(#PCDATA)>
<!ELEMENT comment		(#PCDATA)>
]>


<lexicon lang="swe">
<lemma-entry id="klar_1" form="klar" pos="a" inflection="~t">
	<lexeme id="klar_1_1">
		<definition>som ej innehåller dämpande eller störande inslag</definition>
		<definition-ext>om (flöde av) ljus el. ljud, verkligt el. skenbart</definition-ext>
		<synt-example>~t solsken</synt-example>
		<synt-example>en ~ stråle</synt-example>
		<synt-example>~a gossröster</synt-example>
		<synt-example>en ~ blick</synt-example>
		<synt-example>en spröd, ~ klang</synt-example>
		<synt-example>~a toner från en ensam flöjt</synt-example>
		<compound>klarblå</compound>
	<cycle id="klar_1_1_a">
		<trans>äv. utvidgat om ämne e.d.</trans>
		<synt-example>varmt och ~t väder</synt-example>
		<synt-example>en ~ himmel</synt-example>
		<synt-example>~ buljong</synt-example>
		<synt-example>matt eller ~t glas i glödlampan</synt-example>
		<synt-example>~t badvatten</synt-example>
	</cycle>
	<cycle id="klar_1_1_b">
		<trans>äv. överfört om person, mental förmåga etc.</trans>
		<synt-example>~ i hjärnan</synt-example>
		<synt-example>intellektuellt verkade han helt ~</synt-example>
		<synt-example>den dagen var hon så ~ att det gick att tala med henne</synt-example>
		<compound>förståndsklar</compound>
	</cycle>
	<cycle id="klar_1_1_c">
		<trans>ibl. överfört om motsvarande tidsperiod</trans>
		<synt-example>i sina korta ~a stunder kände hon igen sin dotter</synt-example>
		<synt-example>NN tycktes ha en ~ dag</synt-example>
	</cycle>
	</lexeme>
	<lexeme id="klar_1_2">
		<definition>som enkelt uppfattas och förstås</definition>
		<definition-ext>om ngt som har tankemässigt innehåll; antingen enstaka begrepp el. utsaga om sakförhållande e.d.</definition-ext>
		<synt-example>en ~ definition</synt-example>
		<synt-example>den saken måste man ha ~ för sig</synt-example>
		<synt-example>principen verkar helt ~</synt-example>
		<synt-example>yttrandet hade ~ hänsyftning på NN</synt-example>
		<synt-example>det stod ~t att laget hade fått en ny lirare</synt-example>
		<synt-example>han gjorde ~t att han inte ville medverka</synt-example>
	<cycle id="klar_1_2_a">
		<trans>ibl. äv. ngt bildligt, med föreställning om urskiljbarhet för synsinnet</trans>
		<synt-example>ett glasklart resonemang</synt-example>
		<synt-example>polisen har en ~ bild av hur mordet begicks</synt-example>
	</cycle>
	<cycle id="klar_1_2_b">
		<trans>ofta utvidgat om allmännare företeelser</trans>
		<synt-example>valresultaten har en ~ tendens</synt-example>
		<synt-example>NN har en ~ ledning i rallyt</synt-example>
		<synt-example>en knapp men ~ majoritet</synt-example>
		<synt-example>en ~ förstärkning av konjunkturen</synt-example>
	</cycle>
	<cycle id="klar_1_2_c">
		<trans>ibl. mer utpräglat</trans>
		<synt-example>det är ~t att han kommer</synt-example>
		<synt-example>naturligtvis måste barn hävda sig, den saken är ju ~</synt-example>
		<synt-example>det var Pelle, så ~t!</synt-example>
		<compound>självklar</compound>
	</cycle>
	</lexeme>
	<lexeme id="klar_1_3">
		<definition>som bringats till fullbordat tillstånd</definition>
		<definition-ext>om angiven el. antydd verksamhet, produkt under arbete, etc.</definition-ext>
		<synt-example>maten är ~</synt-example>
		<synt-example>nu är disken ~</synt-example>
		<synt-example>packa ~t (adv.)</synt-example>
		<synt-example>de nya lokalerna står snart ~a</synt-example>
		<synt-example>utredningen beräknas bli ~ vid årsskiftet</synt-example>
	<cycle id="klar_1_3_a">
		<trans>ibl. med samtidig föreställning om tydlighet e.d.</trans>
		<synt-example>det är nu alldeles ~t att landslaget missar VM</synt-example>
		<synt-example>det blev ~t att samarbetsavtalet hade spruckit</synt-example>
	</cycle>
	<cycle id="klar_1_3_b">
		<trans>äv. om person som slutfört ngt</trans>
		<synt-example>han är ~ med sin utbildning</synt-example>
	</cycle>
	<cycle id="klar_1_3_c">
		<trans>äv. (om person el. produkt) med tanke på beredskap för (viss) fortsatt verksamhet el. användning</trans>
		<synt-example>huset är ~t för inflyttning</synt-example>
		<synt-example>hon är ~ att ge sig i väg</synt-example>
	</cycle>
	</lexeme>
	<lexeme id="klar_1_4">
		<definition>som medger säker passage</definition>
		<definition-ext>förbi hinder etc.</definition-ext>
		<synt-example>gå ~ från grundet</synt-example>
	<cycle id="klar_1_4_a">
		<trans>äv. i fråga om abstrakt hinder</trans>
		<synt-example>tullkryssaren var borta och kusten ~ för smugglarna</synt-example>
	</cycle>
	<cycle id="klar_1_4_b">
		<trans>äv. bildligt</trans>
		<synt-example>kusten är ~</synt-example>
	</cycle>
	</lexeme>
</lemma-entry>
<lemma-entry id="stark_1" form="stark" pos="a" inflection="~t">
	<lexeme id="stark_1_1">
		<definition>som har stor muskelkraft</definition>
		<definition-ext>om levande varelse el. (del av) kropp</definition-ext>
		<synt-example>en stor ~ skogshuggare</synt-example>
		<synt-example>~a armar</synt-example>
		<synt-example>~ i benen</synt-example>
		<synt-example>~ som en björn</synt-example>
		<synt-example>den ~ares rätt</synt-example>
	<cycle id="stark_1_1_a">
		<trans>äv. utvidgat i fråga om stor andlig kraft</trans>
		<synt-example>ha ~a nerver</synt-example>
		<synt-example>hon är ~ så hon ska nog klara av krisen</synt-example>
		<synt-example>~ egen vilja</synt-example>
		<synt-example>en ~ personlighet</synt-example>
		<synt-example>teckning är inte hans ~a sida</synt-example>
	</cycle>
	<cycle id="stark_1_1_b">
		<trans>äv.</trans>
		<synt-example>en ~ armé</synt-example>
		<synt-example>en ~ front</synt-example>
		<synt-example>regeringens ~e man</synt-example>
		<synt-example>en ~ regering</synt-example>
		<synt-example>han hade en ~ ställning inom företaget</synt-example>
	</cycle>
	<cycle id="stark_1_1_c">
		<trans>äv. om föremål</trans>
		<synt-example>en ~ nylonlina</synt-example>
	</cycle>
	<cycle id="stark_1_1_d">
		<trans>äv. om företeelse</trans>
		<synt-example>~a vindar</synt-example>
		<synt-example>en ~ kustström</synt-example>
		<synt-example>~ blåst</synt-example>
	</cycle>
	</lexeme>
	<lexeme id="stark_1_2">
		<definition>duktig</definition>
		<definition-ext>i ngt</definition-ext>
		<synt-example>vara ~ i matematik</synt-example>
		<synt-example>det var ~t av honom att bli tvåa</synt-example>
	</lexeme>
	<lexeme id="stark_1_3">
		<definition>som har stor omfattning</definition>
		<synt-example>~ kyla</synt-example>
		<synt-example>~ värme</synt-example>
		<synt-example>han talade med ~ brytning</synt-example>
		<synt-example>~ efterfrågan på arbetskraft</synt-example>
		<synt-example>hon var ~t sminkad (adv.)</synt-example>
		<synt-example>~ artillerield</synt-example>
	<cycle id="stark_1_3_a">
		<trans>särsk. om känsla el. attityd</trans>
		<synt-example>hon kände ~ sorg</synt-example>
		<synt-example>spänningen var ~</synt-example>
		<synt-example>han kände en ~ längtan efter sina barn</synt-example>
		<synt-example>~ lust</synt-example>
		<synt-example>en ~ främlingskänsla</synt-example>
		<synt-example>~ respekt</synt-example>
		<synt-example>hon kände ~ samhörighet med honom</synt-example>
	</cycle>
	<cycle id="stark_1_3_b">
		<trans>äv. neutralt</trans>
		<synt-example>delegationen var 20 man ~</synt-example>
		<synt-example>den 600 sidor ~a volymen</synt-example>
	</cycle>
	</lexeme>
	<lexeme id="stark_1_4">
		<definition>som gör intensivt intryck på sinnena</definition>
		<definition-ext>el. kroppen; särsk. på lukt- och smaksinnet</definition-ext>
		<synt-example>en ~ doft av lavendel</synt-example>
		<synt-example>stanken var ~</synt-example>
		<synt-example>~t kaffe</synt-example>
		<synt-example>~a cigaretter</synt-example>
		<synt-example>~a kryddor</synt-example>
		<synt-example>spaghetti med ~ köttfärssås</synt-example>
		<synt-example>~ senap</synt-example>
		<synt-example>~a mediciner</synt-example>
		<compound>starkdoftande</compound>
		<compound>starksmakande</compound>
	<cycle id="stark_1_4_a">
		<trans>spec. om dryck med hög alkoholhalt</trans>
		<synt-example>~a drycker</synt-example>
		<compound>starksprit</compound>
		<compound>starkvin</compound>
		<compound>starköl</compound>
	</cycle>
	<cycle id="stark_1_4_b">
		<trans>spec. äv. om ljusintryck</trans>
		<synt-example>hans ögon tålde inte det ~a dagsljuset</synt-example>
		<synt-example>~t solljus</synt-example>
		<synt-example>en ~ glödlampa</synt-example>
		<compound>färgstark</compound>
	</cycle>
	<cycle id="stark_1_4_c">
		<trans>spec. äv. om ljudintryck</trans>
		<synt-example>han har en ~ röst</synt-example>
		<synt-example>hon lade en ~ betoning på det sista ordet</synt-example>
		<compound>starktonig</compound>
	</cycle>
	<cycle id="stark_1_4_d">
		<trans>äv. om handling e. d.</trans>
		<synt-example>det är en ~ text i den sången</synt-example>
		<synt-example>en ~ film</synt-example>
	</cycle>
	</lexeme>
	<lexeme id="stark_1_5">
		<definition>vars böjning kännetecknas av vokalväxling</definition>
		<definition-ext>i de olika temaformerna; om verb</definition-ext>
		<synt-example>"springa" är ett ~t verb som böjs "springa, sprang, sprungit"</synt-example>
	<cycle id="stark_1_5_a">
		<trans>äv. i fråga om adjektivböjning</trans>
		<synt-example>~ adjektivböjning har man bl. a. efter obestämd artikel</synt-example>
	</cycle>
	</lexeme>
</lemma-entry>
<lemma-entry id="naturlig_1" form="naturlig" pos="a" inflection="~t">
	<lexeme id="naturlig_1_1">
		<definition>som finns i eller uppkommer ur den ursprungliga, omgivande verkligheten</definition>
		<definition-ext>enl. dess inneboende lagar; om föremål och företeelser som ej framställts el. föreskrivits av människor</definition-ext>
		<synt-example>~ magnet</synt-example>
		<synt-example>den ~a radioaktiva bakgrundsstrålningen</synt-example>
		<synt-example>sjöns ~a fauna</synt-example>
		<synt-example>~t källvatten</synt-example>
		<synt-example>klippan bildade en ~ länstol</synt-example>
		<synt-example>människans ~a förutsättningar för tal</synt-example>
		<synt-example>en ~t uppkommen kreatursras (adv.)</synt-example>
		<synt-example>uppvisa ett ~t rörelsemönster</synt-example>
	<cycle id="naturlig_1_1_a">
		<trans>ofta om skeenden</trans>
		<synt-example>~ befruktning</synt-example>
		<synt-example>~ förlossning</synt-example>
		<synt-example>~a ålderskrämpor</synt-example>
		<synt-example>dö en ~ död</synt-example>
		<synt-example>det ~a urvalet</synt-example>
	</cycle>
	<cycle id="naturlig_1_1_b">
		<trans>äv. allmännare</trans>
		<synt-example>det finns säkert en ~ förklaring till att hon inte är hemma</synt-example>
		<synt-example>det är inte ~t att glömma en sådan sak</synt-example>
	</cycle>
	</lexeme>
	<lexeme id="naturlig_1_2">
		<definition>som framstår såsom självklar</definition>
		<definition-ext>i förh. till de rådande omständigheterna; spec. om person el. företeelse som fyller viss funktion e. d.</definition-ext>
		<synt-example>den ~e kandidaten till ordförandeposten</synt-example>
		<synt-example>problemet får diskuteras i sitt ~a sammanhang</synt-example>
		<synt-example>biblioteket har blivit den ~a samlingsplatsen</synt-example>
		<synt-example>det borde vara ~t att skolan ger handikappade hjälp</synt-example>
		<synt-example>en ~ följdfråga</synt-example>
		<synt-example>av ~a skäl</synt-example>
		<synt-example>~t nog ville hon gå hem (adv.)</synt-example>
	<cycle id="naturlig_1_2_a">
		<trans>äv.</trans>
		<synt-example>musiken ingår som en ~ del i föreställningen</synt-example>
		<synt-example>känna en ~ gemenskap</synt-example>
		<synt-example>han har en ~ auktoritet</synt-example>
	</cycle>
	</lexeme>
	<lexeme id="naturlig_1_3">
		<definition>fri från konstlade spärrar och hämningar</definition>
		<definition-ext>om person el. beteende</definition-ext>
		<synt-example>han har svårt att vara ~ bland folk han inte känner</synt-example>
		<synt-example>~a kontakter mellan människor</synt-example>
		<synt-example>~ sensualism</synt-example>
		<synt-example>~ nakenhet</synt-example>
		<synt-example>skratta ~t (adv.)</synt-example>
		<synt-example>umgås otvunget och ~t med sina vänner (adv.)</synt-example>
	<cycle id="naturlig_1_3_a">
		<trans>ibl. äv. negativt</trans>
		<synt-example>NN:s ungar uppför sig lite väl ~t vid matbordet (adv.)</synt-example>
	</cycle>
	</lexeme>
	<lexeme id="naturlig_1_4">
		<definition>som är bestämd av naturens lagar</definition>
		<synt-example>~ radioaktiv strålning</synt-example>
		<synt-example>sjöns ~a fauna</synt-example>
		<synt-example>vårt ~a rörelsemönster</synt-example>
		<synt-example>~a vattentäkter</synt-example>
		<synt-example>~a ålderskrämpor</synt-example>
		<synt-example>människans ~a förutsättningar för tal</synt-example>
		<synt-example>~ avgång</synt-example>
		<synt-example>dö en ~ död</synt-example>
		<synt-example>det ~a urvalet</synt-example>
		<synt-example>~t källvatten</synt-example>
	<cycle id="naturlig_1_4_a">
		<trans>äv. om avbildning o. d.</trans>
		<synt-example>i ~ storlek</synt-example>
	</cycle>
	</lexeme>
</lemma-entry>
<lemma-entry id="öppen_1" form="öppen" pos="a" inflection="-et -na">
	<lexeme id="öppen_1_1">
		<definition>som är i ett läge som medger direkt kontakt med innanför eller bortanför liggande utrymme</definition>
		<definition-ext>om anordning som är avsedd att kunna spärra kontakt el. tillträde, t. ex. dörr el. lucka</definition-ext>
		<synt-example>sova för -et fönster</synt-example>
		<synt-example>badrumsdörren stod ~ för att släppa ut ångorna</synt-example>
		<synt-example>för att få med sig lasten var han tvungen att köra med bagageluckan ~</synt-example>
		<synt-example>aktörerna fick applåder för ~ ridå</synt-example>
	<cycle id="öppen_1_1_a">
		<trans>äv. om lås e. d., ibl. underförstått</trans>
		<synt-example>hänglåset var -et men inget var stulet</synt-example>
		<synt-example>om jag inte är inne när du kommer så kliv bara på --- ytterdörren är ~</synt-example>
	</cycle>
	<cycle id="öppen_1_1_b">
		<trans>äv. om motsvarande utrymme</trans>
		<synt-example>hamnen brukar frysa vintertid men hålls ~ av isbrytare</synt-example>
		<synt-example>frysen får stå ~ ett tag för att avfrostas</synt-example>
		<synt-example>han brukar lämna bilen ~ så att han inte skall få den uppbruten av tjuvar</synt-example>
		<synt-example>garderoberna var -na</synt-example>
	</cycle>
	<cycle id="öppen_1_1_c">
		<trans>särsk. om kroppsdel etc. som kan vara i motsvarande tillstånd; ibl med symbolisk bibetydelse</trans>
		<synt-example>han lyssnade till nyheten med ~ mun och tom blick</synt-example>
		<synt-example>hon gnuggade sig i ögonen för att försöka hålla dem -na</synt-example>
	</cycle>
	<cycle id="öppen_1_1_d">
		<trans>spec. om mål i bollspel; äv. underförstått</trans>
		<synt-example>NN sköt utanför -et mål</synt-example>
		<synt-example>svenskarna missade flera -na tillfällen</synt-example>
	</cycle>
	<cycle id="öppen_1_1_e">
		<trans>äv. allmännare om ngt som kan karakteriseras med tanke på möjligheter till kontakt e.d.</trans>
		<synt-example>efter vapenstilleståndet är gränsen åter ~</synt-example>
		<synt-example>han fick avtjäna straffet på ~ anstalt</synt-example>
	</cycle>
	<cycle id="öppen_1_1_f">
		<trans>äv. utvidgat om väg e.d. i fråga om avsaknad av hinder för passage, seende etc.</trans>
		<synt-example>ett program som kallades "Öppen kanal"</synt-example>
		<synt-example>de stod i kontakt med räddningsledningen via en ständigt ~ telefonlinje</synt-example>
		<synt-example>isrännan hålls ~ hela vintern</synt-example>
		<synt-example>en ~ vokal kallas så eftersom den uttalas med låg tungställning som föga hindrar luftströmmen</synt-example>
		<synt-example>vid inseglingen bör man hela tiden hålla gapet mellan Flatholmen och Svartskär -et</synt-example>
	</cycle>
	<cycle id="öppen_1_1_g">
		<trans>ofta bildligt i liknelser e. d.</trans>
		<synt-example>motparten håller dörren ~ för fortsatta förhandlingar</synt-example>
		<synt-example>ett gräl för ~ ridå</synt-example>
		<synt-example>det gäller att hålla ögon och öron -na (för vad som händer)</synt-example>
		<synt-example>det inte bara regnade --- himlens portar stod helt -na</synt-example>
	</cycle>
	</lexeme>
	<lexeme id="öppen_1_2">
		<definition>som ej bildar en sammanhållen eller obruten helhet</definition>
		<definition-ext>om ngt som normalt el. ofta har en sluten form, ett hölje e. d.</definition-ext>
		<synt-example>skjortan var ~ i halsen</synt-example>
		<synt-example>boken låg ~ på skrivbordet</synt-example>
		<synt-example>han slog till henne med ~ hand</synt-example>
		<synt-example>hennes famn var ~ för honom</synt-example>
		<synt-example>en kakelugn är mycket effektivare än en ~ spis</synt-example>
		<synt-example>vattnet avleds genom ett -et dike</synt-example>
	<cycle id="öppen_1_2_a">
		<trans>äv. om ohöljd del av ngt</trans>
		<synt-example>lägga förband över ett -et sår</synt-example>
	</cycle>
	<cycle id="öppen_1_2_b">
		<trans>äv. överfört i fråga om avsaknad av begränsning</trans>
		<synt-example>i mängdläran skiljer man på slutna och -na mängder</synt-example>
		<synt-example>ett -et intervall inkluderar inte sina ändpunkter</synt-example>
		<synt-example>med en ~ stavelse menas en stavelse som slutar på vokal</synt-example>
	</cycle>
	</lexeme>
	<lexeme id="öppen_1_3">
		<definition>som ej innehåller ngt som hindrar överblick eller fria rörelser</definition>
		<definition-ext>om utrymme, område etc.</definition-ext>
		<synt-example>byggnadens centrum är en ~ hall med fönster högt under taket</synt-example>
		<synt-example>de -na fjällvidderna</synt-example>
		<synt-example>både skog och ~ terräng</synt-example>
		<synt-example>han blev rånad på ~ gata</synt-example>
		<synt-example>en ~ plats i staden</synt-example>
		<synt-example>-na horisonter</synt-example>
	<cycle id="öppen_1_3_a">
		<trans>äv. mer abstrakt i fråga om känslo- el. tankemässig överblick e.d.</trans>
		<synt-example>planlösningen gör ett -et intryck</synt-example>
		<synt-example>ett ljust och -et musikstycke</synt-example>
		<synt-example>hans skuld ligger i ~ dag</synt-example>
		<synt-example>sova under ~ himmel</synt-example>
		<synt-example>en trots allt ~ och leende värld</synt-example>
	</cycle>
	</lexeme>
	<lexeme id="öppen_1_4">
		<definition>som saknar skydd mot yttre påverkan</definition>
		<definition-ext>särsk. mot naturkrafter e. d.</definition-ext>
		<synt-example>de gav sig ut i en liten ~ båt</synt-example>
		<synt-example>i vårt klimat passar -na bilar illa</synt-example>
		<synt-example>huset ligger -et för alla vindar från västkanten</synt-example>
		<synt-example>staden har ingen hamn, bara en ~ redd</synt-example>
		<synt-example>det är skillnad på att segla i skärgården och att gå ut i ~ sjö</synt-example>
	<cycle id="öppen_1_4_a">
		<trans>spec. i fråga om avsaknad av skydd mot våld el. annat angrepp</trans>
		<synt-example>den ena flygeln var starkt befäst men den andra låg helt ~</synt-example>
		<synt-example>efter den våldsamma högersvingen var boxaren ~ för en vänsterkrok</synt-example>
		<synt-example>han borde inte tagit upp det ämnet, ty där ligger hans tes ~ för motkritik</synt-example>
	</cycle>
	<cycle id="öppen_1_4_b">
		<trans>äv. överfört i fråga om mottaglighet för själslig påverkan, mest med positiv bibetydelse</trans>
		<synt-example>hon är ~ för nya intryck</synt-example>
		<synt-example>en ~ attityd</synt-example>
		<synt-example>jag är ~ för andra förslag till lösningar</synt-example>
		<compound>öppenhet</compound>
	</cycle>
	<cycle id="öppen_1_4_c">
		<trans>äv. med bibetydelse av uppriktighet</trans>
		<synt-example>en ~ och ärlig natur</synt-example>
		<synt-example>ett varmt och -et leende</synt-example>
	</cycle>
	<cycle id="öppen_1_4_d">
		<trans>ibl. med omvänd inriktning</trans>
		<synt-example>laga mat över ~ eld</synt-example>
		<synt-example>en ~ låga skulle kunna vålla en explosion</synt-example>
	</cycle>
	</lexeme>
	<lexeme id="öppen_1_5">
		<definition>som utförs eller äger rum på ett (avsiktligt) tydligt sätt</definition>
		<definition-ext>utan att döljas el. hemlighållas; om utsaga, åsiktsutbyte, motsättning el. annan handling som (direkt el. indirekt) omfattar flera parter</definition-ext>
		<synt-example>vi måste ha en ~ debatt i frågan</synt-example>
		<synt-example>en ~ redovisning av problemen</synt-example>
		<synt-example>tvinga fram ett -et besked</synt-example>
		<synt-example>detta innebär ett -et avståndstagande från den tidigare linjen</synt-example>
		<synt-example>en ~ fientlighet</synt-example>
		<synt-example>jag erkänner -et att misstag har begåtts (adv.)</synt-example>
		<synt-example>svara mig nu -et vad du anser! (adv.)</synt-example>
	<cycle id="öppen_1_5_a">
		<trans>ibl. utvidgat om förhållanden som karakteriseras av detta</trans>
		<synt-example>i landet rådde tidigare en ~ och demokratisk atmosfär</synt-example>
	</cycle>
	<cycle id="öppen_1_5_b">
		<trans>äv. allmännare</trans>
		<synt-example>det rör sig om ~ aggression från stormaktens sida</synt-example>
		<synt-example>hon visade sin kärlek -et (adv.)</synt-example>
		<synt-example>hans motsträvighet övergick i -et trots</synt-example>
		<synt-example>det gäller att bekämpa den -na prostitutionen</synt-example>
	</cycle>
	<cycle id="öppen_1_5_c">
		<trans>äv. konkret</trans>
		<synt-example>du kan inte visa dig -et här i staden (adv.)</synt-example>
		<synt-example>han visade hur man kan spela hem kontraktet med -na kort</synt-example>
		<synt-example>de bar sina vapen -et (adv.)</synt-example>
	</cycle>
	</lexeme>
	<lexeme id="öppen_1_6">
		<definition>direkt tillgänglig för användning eller utnyttjande</definition>
		<definition-ext>vanl. för en större grupp personer; om inrättning e. d.</definition-ext>
		<synt-example>butiken är ~ 9--18 på vardagar och 9--13 på lördagar</synt-example>
		<synt-example>första dagen är mässan endast ~ för pressen</synt-example>
		<synt-example>den mesta sjukvården sker på ~ klinik</synt-example>
		<synt-example>med de nya reglerna försökte man åstadkomma ett universitet -et för alla kategorier</synt-example>
		<synt-example>de bästa spelarna tävlar i ~ klass</synt-example>
		<compound>öppethållande</compound>
	<cycle id="öppen_1_6_a">
		<trans>äv. utvidgat i fråga om tillgänglighet i tiden el. för viss (hög) grad av utnyttjande</trans>
		<synt-example>en ~ fullmakt</synt-example>
		<synt-example>tjänsten hålls ~ för NN</synt-example>
		<synt-example>företaget har en ~ kredit hos banken</synt-example>
		<synt-example>ett konto hålls -et för detta ändamål</synt-example>
	</cycle>
	<cycle id="öppen_1_6_b">
		<trans>äv. allmännare för att ange valfrihet e. d.</trans>
		<synt-example>det står dig -et att göra som du vill</synt-example>
		<synt-example>regeringens dementi lämnar fältet -et för spekulationer</synt-example>
	</cycle>
	</lexeme>
	<lexeme id="öppen_1_7">
		<definition>som ej har avslutats eller fullbordats</definition>
		<definition-ext>om skeende men äv.om tankegång e.d.</definition-ext>
		<synt-example>vi måste tills vidare lämna frågan ~</synt-example>
		<synt-example>saken får stå ~</synt-example>
		<synt-example>här fordras en ~ stadsplanering i stället för detaljregleringar</synt-example>
		<synt-example>Syd höll budgivningen ~ genom att bjuda 1 sang</synt-example>
	<cycle id="öppen_1_7_a">
		<trans>äv. om oförutsägbart resultat av skeende etc.</trans>
		<synt-example>det tredje loppet på V-65 är helt -et --- vilken som helst av fem hästar kan vinna</synt-example>
	</cycle>
	<cycle id="öppen_1_7_b">
		<trans>äv. utvidgat för att ange tänkbara i st. f. faktiska möjligheter e. d.</trans>
		<synt-example>en dikt vars religiösa innebörd är ~</synt-example>
		<synt-example>en ~ teaterföreställning som inte försöker tvinga på publiken en enda sanning</synt-example>
		<synt-example>vi behöver en ~ bildkonst</synt-example>
	</cycle>
	</lexeme>
</lemma-entry>
<lemma-entry id="bred_1" form="bred" pos="a" inflection="brett">
	<lexeme id="bred_1_1">
		<definition>som har stor utsträckning på tvären mot (tänkt) huvudriktning</definition>
		<definition-ext>normalt i vågrätt läge</definition-ext>
		<synt-example>en stor och ~ karl</synt-example>
		<synt-example>en ~ gata kantad med träd</synt-example>
		<synt-example>en duk med ~a spetsar</synt-example>
		<synt-example>en ~ dubbelsäng</synt-example>
		<synt-example>en kort och ~ näsa</synt-example>
		<synt-example>~ över ändan</synt-example>
		<synt-example>ett brett leende</synt-example>
		<synt-example>hon stod med benen brett isär (adv.)</synt-example>
	<cycle id="bred_1_1_a">
		<trans>äv. neutralt</trans>
		<synt-example>floden är två kilometer ~</synt-example>
		<compound>milsbred</compound>
	</cycle>
	</lexeme>
	<lexeme id="bred_1_2">
		<definition>som omfattar en förhållandevis stor mängd (typer av) företeelser</definition>
		<definition-ext>på visst område e. d.</definition-ext>
		<synt-example>en ~ koalitionsregering</synt-example>
		<synt-example>försöka hitta ~a lösningar</synt-example>
		<synt-example>på ~ front</synt-example>
		<synt-example>med ~ folklig förankring</synt-example>
		<synt-example>ha ett brett register</synt-example>
	</lexeme>
	<lexeme id="bred_1_3">
	</lexeme>
</lemma-entry>
<lemma-entry id="flytta_1" form="flytta" pos="v" inflection="-ade -at">
	<lexeme id="flytta_1_1">
		<definition>föra till annan plats</definition>
		<synt-example>~ flygeln till finrummet</synt-example>